# Football Analytics Platform

## Chapter 1: Data Understanding

This notebook explores the StatsBomb Open Data dataset to understand its structure before preparing it for machine learning.

In [1]:
import json
import os
import pandas as pd
from pathlib import Path

In [2]:
Path.cwd()

WindowsPath('c:/Users/Kenda/OneDrive/Documentos/Football-Analytics-Platform')

In [3]:
data_folder = Path("open-data-master/data/events")

print(data_folder.exists())

True

In [4]:
event_files = os.listdir(data_folder)

print("Number of matches:", len(event_files))
print("First 10 match files:")
print(event_files[:10])

Number of matches: 4235
First 10 match files:
['15946.json', '15956.json', '15973.json', '15978.json', '15986.json', '15998.json', '16010.json', '16023.json', '16029.json', '16056.json']

In [5]:
match_file = data_folder / event_files[0]

with open(match_file, "r", encoding="utf-8") as file:
    events = json.load(file)

print(type(events))
print("Number of events:", len(events))

<class 'list'>
Number of events: 3762

In [6]:
events[0]

{'id': '9f6e2ecf-6685-45df-a62e-c2db3090f6c1',
 'index': 1,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 35, 'name': 'Starting XI'},
 'possession': 1,
 'possession_team': {'id': 217, 'name': 'Barcelona'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 217, 'name': 'Barcelona'},
 'duration': 0.0,
 'tactics': {'formation': 442,
  'lineup': [{'player': {'id': 20055, 'name': 'Marc-André ter Stegen'},
    'position': {'id': 1, 'name': 'Goalkeeper'},
    'jersey_number': 1},
   {'player': {'id': 6374, 'name': 'Nélson Cabral Semedo'},
    'position': {'id': 2, 'name': 'Right Back'},
    'jersey_number': 2},
   {'player': {'id': 5213, 'name': 'Gerard Piqué Bernabéu'},
    'position': {'id': 3, 'name': 'Right Center Back'},
    'jersey_number': 3},
   {'player': {'id': 5492, 'name': 'Samuel Yves Umtiti'},
    'position': {'id': 5, 'name': 'Left Center Back'},
    'jersey_number': 23},
   {'player': {'id': 5211, 'name': 'Jordi Alba Ramos'},
    'position': {'id': 6, 'name': 'Left Back'},
    'jersey_number': 18},
   {'player': {'id': 5203, 'name': 'Sergio Busquets i Burgos'},
    'position': {'id': 9, 'name': 'Right Defensive Midfield'},
    'jersey_number': 5},
   {'player': {'id': 5470, 'name': 'Ivan Rakitić'},
    'position': {'id': 11, 'name': 'Left Defensive Midfield'},
    'jersey_number': 4},
   {'player': {'id': 6379, 'name': 'Sergi Roberto Carnicer'},
    'position': {'id': 12, 'name': 'Right Midfield'},
    'jersey_number': 20},
   {'player': {'id': 5477, 'name': 'Ousmane Dembélé'},
    'position': {'id': 16, 'name': 'Left Midfield'},
    'jersey_number': 11},
   {'player': {'id': 5246, 'name': 'Luis Alberto Suárez Díaz'},
    'position': {'id': 22, 'name': 'Right Center Forward'},
    'jersey_number': 9},
   {'player': {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'},
    'position': {'id': 24, 'name': 'Left Center Forward'},
    'jersey_number': 10}]}}

In [7]:
event_files = os.listdir(data_folder)

print("Number of matches:", len(event_files))
print("First 10 match files:")
print(event_files[:10])

Number of matches: 4235
First 10 match files:
['15946.json', '15956.json', '15973.json', '15978.json', '15986.json', '15998.json', '16010.json', '16023.json', '16029.json', '16056.json']

In [8]:
match_file = data_folder / event_files[0]

with open(match_file, "r", encoding="utf-8") as file:
    events = json.load(file)

print(type(events))
print("Number of events:", len(events))

<class 'list'>
Number of events: 3762

In [9]:
events[1]

{'id': '0300039d-150d-41e4-b29a-76602ef002e6',
 'index': 2,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 35, 'name': 'Starting XI'},
 'possession': 1,
 'possession_team': {'id': 217, 'name': 'Barcelona'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 206, 'name': 'Deportivo Alavés'},
 'duration': 0.0,
 'tactics': {'formation': 451,
  'lineup': [{'player': {'id': 6629, 'name': 'Fernando Pacheco Flores'},
    'position': {'id': 1, 'name': 'Goalkeeper'},
    'jersey_number': 1},
   {'player': {'id': 6618, 'name': 'Martín Aguirregabiria Padilla'},
    'position': {'id': 2, 'name': 'Right Back'},
    'jersey_number': 21},
   {'player': {'id': 6615, 'name': 'Víctor Laguardia Cisneros'},
    'position': {'id': 3, 'name': 'Right Center Back'},
    'jersey_number': 5},
   {'player': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
    'position': {'id': 5, 'name': 'Left Center Back'},
    'jersey_number': 6},
   {'player': {'id': 6612, 'name': 'Rubén Duarte Sánchez'},
    'position': {'id': 6, 'name': 'Left Back'},
    'jersey_number': 3},
   {'player': {'id': 6839, 'name': 'Daniel Alejandro Torres Rojas'},
    'position': {'id': 10, 'name': 'Center Defensive Midfield'},
    'jersey_number': 16},
   {'player': {'id': 6617, 'name': 'Ibai Gómez Pérez'},
    'position': {'id': 12, 'name': 'Right Midfield'},
    'jersey_number': 11},
   {'player': {'id': 6626, 'name': 'Mubarak Wakaso'},
    'position': {'id': 13, 'name': 'Right Center Midfield'},
    'jersey_number': 22},
   {'player': {'id': 6632, 'name': 'Manuel Alejandro García Sánchez'},
    'position': {'id': 15, 'name': 'Left Center Midfield'},
    'jersey_number': 19},
   {'player': {'id': 6581, 'name': 'Jonathan Rodríguez Menéndez'},
    'position': {'id': 16, 'name': 'Left Midfield'},
    'jersey_number': 23},
   {'player': {'id': 6613, 'name': 'Rubén Sobrino Pozuelo'},
    'position': {'id': 23, 'name': 'Center Forward'},
    'jersey_number': 7}]}}

In [10]:
events[2]

{'id': '491e8901-7630-4cc8-b57b-937dddff2eaa',
 'index': 3,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 18, 'name': 'Half Start'},
 'possession': 1,
 'possession_team': {'id': 217, 'name': 'Barcelona'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 217, 'name': 'Barcelona'},
 'duration': 0.0,
 'related_events': ['757b85ad-ddfe-44d5-b893-c23a9fb709d8']}

In [11]:
events[0].keys()

dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics'])

In [12]:
df = pd.DataFrame(events)

In [13]:
df.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,goalkeeper,clearance,block,dribble,foul_committed,foul_won,out,miscontrol,bad_behaviour,substitution
0,9f6e2ecf-6685-45df-a62e-c2db3090f6c1,1,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0300039d-150d-41e4-b29a-76602ef002e6,2,1,00:00:00.000,0,0,"{'id': 35, 'name': 'Starting XI'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,491e8901-7630-4cc8-b57b-937dddff2eaa,3,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,757b85ad-ddfe-44d5-b893-c23a9fb709d8,4,1,00:00:00.000,0,0,"{'id': 18, 'name': 'Half Start'}",1,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,5,1,00:00:00.575,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 206, 'name': 'Deportivo Alavés'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'duration',
       'tactics', 'related_events', 'player', 'position', 'location', 'pass',
       'carry', 'ball_receipt', 'under_pressure', 'duel', 'counterpress',
       'interception', 'off_camera', 'ball_recovery', 'shot', 'goalkeeper',
       'clearance', 'block', 'dribble', 'foul_committed', 'foul_won', 'out',
       'miscontrol', 'bad_behaviour', 'substitution'],
      dtype='str')

In [15]:
df.shape

(3762, 37)

In [16]:
df["type"]

0       {'id': 35, 'name': 'Starting XI'}
1       {'id': 35, 'name': 'Starting XI'}
2        {'id': 18, 'name': 'Half Start'}
3        {'id': 18, 'name': 'Half Start'}
4              {'id': 30, 'name': 'Pass'}
                      ...
3757       {'id': 17, 'name': 'Pressure'}
3758           {'id': 16, 'name': 'Shot'}
3759    {'id': 23, 'name': 'Goal Keeper'}
3760       {'id': 34, 'name': 'Half End'}
3761       {'id': 34, 'name': 'Half End'}
Name: type, Length: 3762, dtype: object

In [17]:
df["type"]

0       {'id': 35, 'name': 'Starting XI'}
1       {'id': 35, 'name': 'Starting XI'}
2        {'id': 18, 'name': 'Half Start'}
3        {'id': 18, 'name': 'Half Start'}
4              {'id': 30, 'name': 'Pass'}
                      ...
3757       {'id': 17, 'name': 'Pressure'}
3758           {'id': 16, 'name': 'Shot'}
3759    {'id': 23, 'name': 'Goal Keeper'}
3760       {'id': 34, 'name': 'Half End'}
3761       {'id': 34, 'name': 'Half End'}
Name: type, Length: 3762, dtype: object

In [18]:
df["event_type"] = df["type"].apply(lambda x: x["name"] if isinstance(x, dict) else None)

df["event_type"].head(20)

0       Starting XI
1       Starting XI
2        Half Start
3        Half Start
4              Pass
5     Ball Receipt*
6             Carry
7              Pass
8     Ball Receipt*
9              Duel
10             Pass
11    Ball Receipt*
12             Pass
13    Ball Receipt*
14            Carry
15             Pass
16    Ball Receipt*
17             Pass
18    Ball Recovery
19            Carry
Name: event_type, dtype: str

In [19]:
df["event_type"].value_counts()

event_type
Pass              1163
Ball Receipt*     1058
Carry              890
Pressure           212
Ball Recovery       89
Duel                53
Clearance           37
Goal Keeper         34
Block               32
Shot                28
Interception        24
Dribble             24
Foul Committed      23
Dispossessed        21
Foul Won            21
Miscontrol          17
Dribbled Past       14
Substitution         6
Half Start           4
Half End             4
Tactical Shift       4
Starting XI          2
Bad Behaviour        1
Error                1
Name: count, dtype: int64

In [20]:
df["event_type"] = df["type"].apply(lambda x: x["name"] if isinstance(x, dict) else None)

df["event_type"].head(20)

0       Starting XI
1       Starting XI
2        Half Start
3        Half Start
4              Pass
5     Ball Receipt*
6             Carry
7              Pass
8     Ball Receipt*
9              Duel
10             Pass
11    Ball Receipt*
12             Pass
13    Ball Receipt*
14            Carry
15             Pass
16    Ball Receipt*
17             Pass
18    Ball Recovery
19            Carry
Name: event_type, dtype: str

In [21]:
df["event_type"].value_counts()

event_type
Pass              1163
Ball Receipt*     1058
Carry              890
Pressure           212
Ball Recovery       89
Duel                53
Clearance           37
Goal Keeper         34
Block               32
Shot                28
Interception        24
Dribble             24
Foul Committed      23
Dispossessed        21
Foul Won            21
Miscontrol          17
Dribbled Past       14
Substitution         6
Half Start           4
Half End             4
Tactical Shift       4
Starting XI          2
Bad Behaviour        1
Error                1
Name: count, dtype: int64

In [22]:
passes = df[df["event_type"] == "Pass"]

passes.head()

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,clearance,block,dribble,foul_committed,foul_won,out,miscontrol,bad_behaviour,substitution,event_type
4,549567bd-36de-4ac8-b8dc-6b5d3f1e4be8,5,1,00:00:00.575,0,0,"{'id': 30, 'name': 'Pass'}",2,"{'id': 206, 'name': 'Deportivo Alavés'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass
7,4e4e4cad-9897-43ec-842d-585a4077f6ce,8,1,00:00:03.864,0,3,"{'id': 30, 'name': 'Pass'}",2,"{'id': 206, 'name': 'Deportivo Alavés'}","{'id': 9, 'name': 'From Kick Off'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass
10,be27cc25-92b5-4696-b43c-aad957a6119a,11,1,00:00:07.152,0,7,"{'id': 30, 'name': 'Pass'}",3,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass
12,b33c0b7f-7456-4efe-b43c-5fd7cbd14689,13,1,00:00:08.848,0,8,"{'id': 30, 'name': 'Pass'}",3,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass
15,c587e5ce-fe6e-4cfb-b510-8a8e193699d3,16,1,00:00:10.873,0,10,"{'id': 30, 'name': 'Pass'}",3,"{'id': 217, 'name': 'Barcelona'}","{'id': 1, 'name': 'Regular Play'}",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass

In [23]:
len(passes)

1163

In [24]:
passes.iloc[0]

id                              549567bd-36de-4ac8-b8dc-6b5d3f1e4be8
index                                                              5
period                                                             1
timestamp                                               00:00:00.575
minute                                                             0
second                                                             0
type                                      {'id': 30, 'name': 'Pass'}
possession                                                         2
possession_team              {'id': 206, 'name': 'Deportivo Alavés'}
play_pattern                      {'id': 9, 'name': 'From Kick Off'}
team                         {'id': 206, 'name': 'Deportivo Alavés'}
duration                                                    2.015669
tactics                                                          NaN
related_events                [b56799eb-083a-4e28-bc70-78b77496cdfc]
player             {'id': 6581, 'name': 'Jonathan Rodríguez Menén...
position                         {'id': 16, 'name': 'Left Midfield'}
location                                                [61.0, 40.1]
pass               {'recipient': {'id': 6855, 'name': 'Guillermo ...
carry                                                            NaN
ball_receipt                                                     NaN
under_pressure                                                   NaN
duel                                                             NaN
counterpress                                                     NaN
interception                                                     NaN
off_camera                                                       NaN
ball_recovery                                                    NaN
shot                                                             NaN
goalkeeper                                                       NaN
clearance                                                        NaN
block                                                            NaN
dribble                                                          NaN
foul_committed                                                   NaN
foul_won                                                         NaN
out                                                              NaN
miscontrol                                                       NaN
bad_behaviour                                                    NaN
substitution                                                     NaN
event_type                                                      Pass
Name: 4, dtype: object

In [25]:
events[2]

{'id': '491e8901-7630-4cc8-b57b-937dddff2eaa',
 'index': 3,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 18, 'name': 'Half Start'},
 'possession': 1,
 'possession_team': {'id': 217, 'name': 'Barcelona'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 217, 'name': 'Barcelona'},
 'duration': 0.0,
 'related_events': ['757b85ad-ddfe-44d5-b893-c23a9fb709d8']}

In [26]:
events[3]

{'id': '757b85ad-ddfe-44d5-b893-c23a9fb709d8',
 'index': 4,
 'period': 1,
 'timestamp': '00:00:00.000',
 'minute': 0,
 'second': 0,
 'type': {'id': 18, 'name': 'Half Start'},
 'possession': 1,
 'possession_team': {'id': 217, 'name': 'Barcelona'},
 'play_pattern': {'id': 1, 'name': 'Regular Play'},
 'team': {'id': 206, 'name': 'Deportivo Alavés'},
 'duration': 0.0,
 'related_events': ['491e8901-7630-4cc8-b57b-937dddff2eaa']}

In [27]:

passes = df[df["event_type"] == "Pass"]

In [28]:
len(passes)

1163

In [29]:
passes.iloc[0]["pass"]

{'recipient': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
 'length': 29.76995,
 'angle': -2.7230272,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [33.8, 28.0],
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 65, 'name': 'Kick Off'}}

In [30]:
passes["recipient"] = passes["pass"].apply(
    lambda x: x.get("recipient", {}).get("name")
    if isinstance(x, dict) else None
)

In [31]:
passes["pass_length"] = passes["pass"].apply(
    lambda x: x.get("length")
    if isinstance(x, dict) else None
)

In [32]:
passes["completed"] = passes["pass"].apply(
    lambda x: "Yes"
    if isinstance(x, dict) and "outcome" not in x
    else "No"
)

In [33]:
passes["completed"].value_counts()

completed
Yes    984
No     179
Name: count, dtype: int64

In [34]:
passes.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'duration',
 'tactics',
 'related_events',
 'player',
 'position',
 'location',
 'pass',
 'carry',
 'ball_receipt',
 'under_pressure',
 'duel',
 'counterpress',
 'interception',
 'off_camera',
 'ball_recovery',
 'shot',
 'goalkeeper',
 'clearance',
 'block',
 'dribble',
 'foul_committed',
 'foul_won',
 'out',
 'miscontrol',
 'bad_behaviour',
 'substitution',
 'event_type',
 'recipient',
 'pass_length',
 'completed']

In [35]:
passes["player_name"] = passes["player"].apply(
    lambda x: x.get("name") if isinstance(x, dict) else None
)

In [36]:
passes[["player_name", "recipient", "completed"]].head()

,player_name,recipient,completed
4,Jonathan Rodríguez Menéndez,Guillermo Alfonso Maripán Loaysa,Yes
7,Guillermo Alfonso Maripán Loaysa,Rubén Sobrino Pozuelo,No
10,Sergio Busquets i Burgos,Ivan Rakitić,Yes
12,Ivan Rakitić,Ousmane Dembélé,Yes
15,Ousmane Dembélé,Jordi Alba Ramos,Yes

In [37]:
passes["player_name"].value_counts().head(10)

player_name
Ivan Rakitić                      138
Jordi Alba Ramos                  128
Lionel Andrés Messi Cuccittini     91
Sergi Roberto Carnicer             89
Sergio Busquets i Burgos           83
Gerard Piqué Bernabéu              81
Ousmane Dembélé                    67
Samuel Yves Umtiti                 65
Philippe Coutinho Correia          52
Luis Alberto Suárez Díaz           39
Name: count, dtype: int64

In [38]:
player_stats = (
    passes.groupby("player_name")
    .agg(
        total_passes=("completed", "count"),
        completed_passes=("completed", lambda x: (x == "Yes").sum())
    )
)

player_stats["pass_completion_%"] = (
    player_stats["completed_passes"]
    / player_stats["total_passes"]
) * 100

player_stats = player_stats.sort_values(
    by="pass_completion_%",
    ascending=False
)

player_stats.head(11)

,total_passes,completed_passes,pass_completion_%
player_name,,,
Arturo Erasmo Vidal Pardo,7,7,100.000000
Samuel Yves Umtiti,65,63,96.923077
Nélson Cabral Semedo,32,31,96.875000
Marc-André ter Stegen,27,26,96.296296
Arthur Henrique Ramos de Oliveira Melo,18,17,94.444444
Gerard Piqué Bernabéu,81,76,93.827160
Ivan Rakitić,138,129,93.478261
Sergio Busquets i Burgos,83,77,92.771084
Jordi Alba Ramos,128,117,91.406250
Sergi Roberto Carnicer,89,79,88.764045
Philippe Coutinho Correia,52,46,88.461538

In [39]:
len(player_stats)

28

In [40]:
player_stats

,total_passes,completed_passes,pass_completion_%
player_name,,,
Arturo Erasmo Vidal Pardo,7,7,100.000000
Samuel Yves Umtiti,65,63,96.923077
Nélson Cabral Semedo,32,31,96.875000
Marc-André ter Stegen,27,26,96.296296
Arthur Henrique Ramos de Oliveira Melo,18,17,94.444444
Gerard Piqué Bernabéu,81,76,93.827160
Ivan Rakitić,138,129,93.478261
Sergio Busquets i Burgos,83,77,92.771084
Jordi Alba Ramos,128,117,91.406250
Sergi Roberto Carnicer,89,79,88.764045
Philippe Coutinho Correia,52,46,88.461538
Rubén Sobrino Pozuelo,19,16,84.210526
Jorge Franco Alviz,12,10,83.333333
Lionel Andrés Messi Cuccittini,91,75,82.417582
Manuel Alejandro García Sánchez,21,16,76.190476
Rubén Duarte Sánchez,25,19,76.000000
Daniel Alejandro Torres Rojas,16,12,75.000000
Ousmane Dembélé,67,49,73.134328
Luis Alberto Suárez Díaz,39,28,71.794872
Adrián Marín Gómez,7,5,71.428571
Guillermo Alfonso Maripán Loaysa,16,11,68.750000
Mubarak Wakaso,22,15,68.181818
Ibai Gómez Pérez,34,23,67.647059
Borja González Tomás,6,4,66.666667
Víctor Laguardia Cisneros,11,7,63.636364
Jonathan Rodríguez Menéndez,11,6,54.545455
Fernando Pacheco Flores,26,12,46.153846
Martín Aguirregabiria Padilla,20,8,40.000000

In [41]:
passes.iloc[0]["location"]

[61.0, 40.1]

In [42]:
passes.iloc[0]["pass"]["end_location"]

[33.8, 28.0]

In [43]:
passes["start_x"] = passes["location"].apply(
    lambda x: x[0] if isinstance(x, list) else None
)

In [44]:
passes["end_x"] = passes["pass"].apply(
    lambda x: x.get("end_location")[0]
    if isinstance(x, dict) and "end_location" in x
    else None
)

In [45]:
passes["forward_distance"] = (
    passes["end_x"] - passes["start_x"]
)

In [46]:
passes[
    [
        "player_name",
        "start_x",
        "end_x",
        "forward_distance"
    ]
].head()

                         player_name  start_x  end_x  forward_distance
4        Jonathan Rodríguez Menéndez     61.0   33.8             -27.2
7   Guillermo Alfonso Maripán Loaysa     36.8   86.5              49.7
10          Sergio Busquets i Burgos     33.6   35.1               1.5
12                      Ivan Rakitić     35.1   36.2               1.1
15                   Ousmane Dembélé     34.3   25.3              -9.0

In [47]:
passes.iloc[0]["pass"]

{'recipient': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
 'length': 29.76995,
 'angle': -2.7230272,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [33.8, 28.0],
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 65, 'name': 'Kick Off'}}

In [48]:
passes["progressive"] = passes["forward_distance"] >= 10

In [49]:
passes["progressive"].value_counts()

progressive
False    800
True     363
Name: count, dtype: int64

In [50]:
progressive_stats = (
    passes.groupby("player_name")["progressive"]
    .sum()
    .sort_values(ascending=False)
)

progressive_stats.head(10)

player_name
Ivan Rakitić                      53
Gerard Piqué Bernabéu             27
Samuel Yves Umtiti                26
Lionel Andrés Messi Cuccittini    26
Sergio Busquets i Burgos          24
Fernando Pacheco Flores           22
Marc-André ter Stegen             21
Sergi Roberto Carnicer            18
Jordi Alba Ramos                  18
Ibai Gómez Pérez                  14
Name: progressive, dtype: int64

In [51]:
passes.iloc[0]["pass"]

{'recipient': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
 'length': 29.76995,
 'angle': -2.7230272,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [33.8, 28.0],
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 65, 'name': 'Kick Off'}}

In [52]:
df.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'duration',
 'tactics',
 'related_events',
 'player',
 'position',
 'location',
 'pass',
 'carry',
 'ball_receipt',
 'under_pressure',
 'duel',
 'counterpress',
 'interception',
 'off_camera',
 'ball_recovery',
 'shot',
 'goalkeeper',
 'clearance',
 'block',
 'dribble',
 'foul_committed',
 'foul_won',
 'out',
 'miscontrol',
 'bad_behaviour',
 'substitution',
 'event_type']

In [53]:
df.head

<bound method NDFrame.head of                                         id  index  period     timestamp  \
0     9f6e2ecf-6685-45df-a62e-c2db3090f6c1      1       1  00:00:00.000
1     0300039d-150d-41e4-b29a-76602ef002e6      2       1  00:00:00.000
2     491e8901-7630-4cc8-b57b-937dddff2eaa      3       1  00:00:00.000
3     757b85ad-ddfe-44d5-b893-c23a9fb709d8      4       1  00:00:00.000
4     549567bd-36de-4ac8-b8dc-6b5d3f1e4be8      5       1  00:00:00.575
...                                    ...    ...     ...           ...
3757  910d8478-49bf-4b05-9023-9af868c6222e   3758       2  00:46:41.185
3758  036c1a04-8d9b-40c0-8b35-780df67fab4d   3759       2  00:46:43.032
3759  be34da5e-38ac-4c7b-8e65-813b2e70ffe5   3760       2  00:46:43.426
3760  15ac0641-73da-4b58-bb73-a18934727eac   3761       2  00:47:31.061
3761  57539da1-a939-4e34-be29-7408942de747   3762       2  00:47:31.061

      minute  second                               type  possession  \
0          0       0  {'id': 35, 'name': 'Starting XI'}           1
1          0       0  {'id': 35, 'name': 'Starting XI'}           1
2          0       0   {'id': 18, 'name': 'Half Start'}           1
3          0       0   {'id': 18, 'name': 'Half Start'}           1
4          0       0         {'id': 30, 'name': 'Pass'}           2
...      ...     ...                                ...         ...
3757      91      41     {'id': 17, 'name': 'Pressure'}         143
3758      91      43         {'id': 16, 'name': 'Shot'}         143
3759      91      43  {'id': 23, 'name': 'Goal Keeper'}         143
3760      92      31     {'id': 34, 'name': 'Half End'}         143
3761      92      31     {'id': 34, 'name': 'Half End'}         143

                              possession_team  \
0            {'id': 217, 'name': 'Barcelona'}
1            {'id': 217, 'name': 'Barcelona'}
2            {'id': 217, 'name': 'Barcelona'}
3            {'id': 217, 'name': 'Barcelona'}
4     {'id': 206, 'name': 'Deportivo Alavés'}
...                                       ...
3757         {'id': 217, 'name': 'Barcelona'}
3758         {'id': 217, 'name': 'Barcelona'}
3759         {'id': 217, 'name': 'Barcelona'}
3760         {'id': 217, 'name': 'Barcelona'}
3761         {'id': 217, 'name': 'Barcelona'}

                            play_pattern  ... clearance  block dribble  \
0      {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
1      {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
2      {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
3      {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
4     {'id': 9, 'name': 'From Kick Off'}  ...       NaN    NaN     NaN
...                                  ...  ...       ...    ...     ...
3757   {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
3758   {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
3759   {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
3760   {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN
3761   {'id': 1, 'name': 'Regular Play'}  ...       NaN    NaN     NaN

     foul_committed foul_won  out miscontrol bad_behaviour substitution  \
0               NaN      NaN  NaN        NaN           NaN          NaN
1               NaN      NaN  NaN        NaN           NaN          NaN
2               NaN      NaN  NaN        NaN           NaN          NaN
3               NaN      NaN  NaN        NaN           NaN          NaN
4               NaN      NaN  NaN        NaN           NaN          NaN
...             ...      ...  ...        ...           ...          ...
3757            NaN      NaN  NaN        NaN           NaN          NaN
3758            NaN      NaN  NaN        NaN           NaN          NaN
3759            NaN      NaN  NaN        NaN           NaN          NaN
3760            NaN      NaN  NaN        NaN           NaN          NaN
3761            NaN      NaN  NaN        NaN           NaN          NaN

       event_type
0     Starting XI
1     Starting XI
2      Half Start
3      Half Start
4            Pass
...           ...
3757     Pressure
3758         Shot
3759  Goal Keeper
3760     Half End
3761     Half End

[3762 rows x 38 columns]>

In [54]:
df.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'duration',
 'tactics',
 'related_events',
 'player',
 'position',
 'location',
 'pass',
 'carry',
 'ball_receipt',
 'under_pressure',
 'duel',
 'counterpress',
 'interception',
 'off_camera',
 'ball_recovery',
 'shot',
 'goalkeeper',
 'clearance',
 'block',
 'dribble',
 'foul_committed',
 'foul_won',
 'out',
 'miscontrol',
 'bad_behaviour',
 'substitution',
 'event_type']

In [55]:
passes[["player_name", "related_events"]].head()

,player_name,related_events
4,Jonathan Rodríguez Menéndez,[b56799eb-083a-4e28-bc70-78b77496cdfc]
7,Guillermo Alfonso Maripán Loaysa,"[0e1a221a-1b99-453c-bb23-396517770684, be27cc2..."
10,Sergio Busquets i Burgos,"[4e4e4cad-9897-43ec-842d-585a4077f6ce, c8eeb78..."
12,Ivan Rakitić,[a0eee1dc-b5fc-40e6-ae5c-7d57d860fe4f]
15,Ousmane Dembélé,[3ef3659a-b158-4bc1-96ac-08e55e19606d]

In [56]:
first_id = passes.iloc[0]["related_events"][0]

print(first_id)

b56799eb-083a-4e28-bc70-78b77496cdfc

In [57]:
df[df["id"] == first_id][["event_type", "player", "minute", "second"]]

,event_type,player,minute,second
5,Ball Receipt*,"{'id': 6855, 'name': 'Guillermo Alfonso Maripá...",0,2

In [58]:
 passes.iloc[0]

id                               549567bd-36de-4ac8-b8dc-6b5d3f1e4be8
index                                                               5
period                                                              1
timestamp                                                00:00:00.575
minute                                                              0
second                                                              0
type                                       {'id': 30, 'name': 'Pass'}
possession                                                          2
possession_team               {'id': 206, 'name': 'Deportivo Alavés'}
play_pattern                       {'id': 9, 'name': 'From Kick Off'}
team                          {'id': 206, 'name': 'Deportivo Alavés'}
duration                                                     2.015669
tactics                                                           NaN
related_events                 [b56799eb-083a-4e28-bc70-78b77496cdfc]
player              {'id': 6581, 'name': 'Jonathan Rodríguez Menén...
position                          {'id': 16, 'name': 'Left Midfield'}
location                                                 [61.0, 40.1]
pass                {'recipient': {'id': 6855, 'name': 'Guillermo ...
carry                                                             NaN
ball_receipt                                                      NaN
under_pressure                                                    NaN
duel                                                              NaN
counterpress                                                      NaN
interception                                                      NaN
off_camera                                                        NaN
ball_recovery                                                     NaN
shot                                                              NaN
goalkeeper                                                        NaN
clearance                                                         NaN
block                                                             NaN
dribble                                                           NaN
foul_committed                                                    NaN
foul_won                                                          NaN
out                                                               NaN
miscontrol                                                        NaN
bad_behaviour                                                     NaN
substitution                                                      NaN
event_type                                                       Pass
recipient                            Guillermo Alfonso Maripán Loaysa
pass_length                                                  29.76995
completed                                                         Yes
player_name                               Jonathan Rodríguez Menéndez
start_x                                                          61.0
end_x                                                            33.8
forward_distance                                                -27.2
progressive                                                     False
Name: 4, dtype: object

In [59]:
passes.iloc[0]["pass"]

{'recipient': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
 'length': 29.76995,
 'angle': -2.7230272,
 'height': {'id': 1, 'name': 'Ground Pass'},
 'end_location': [33.8, 28.0],
 'body_part': {'id': 38, 'name': 'Left Foot'},
 'type': {'id': 65, 'name': 'Kick Off'}}

In [60]:
passes.iloc[0]["pass"]["length"]

29.76995

In [61]:
all_pass_keys = set()

for pass_data in passes["pass"]:
    if isinstance(pass_data, dict):
        all_pass_keys.update(pass_data.keys())

sorted(all_pass_keys)

['aerial_won',
 'angle',
 'assisted_shot_id',
 'body_part',
 'cross',
 'cut_back',
 'deflected',
 'end_location',
 'goal_assist',
 'height',
 'inswinging',
 'length',
 'miscommunication',
 'no_touch',
 'outcome',
 'recipient',
 'shot_assist',
 'straight',
 'switch',
 'technique',
 'through_ball',
 'type']

In [62]:
passes["key_pass"] = passes["pass"].apply(
    lambda x: x.get("shot_assist", False)
    if isinstance(x, dict)
    else False
)

In [63]:
passes["key_pass"].value_counts()

key_pass
False    1147
True       16
Name: count, dtype: int64

In [64]:
passes.loc[
    passes["key_pass"],
    [
        "minute",
        "second",
        "player_name",
        "recipient",
        "pass_length"
    ]
]

,minute,second,player_name,recipient,pass_length
133,2,24,Ivan Rakitić,Lionel Andrés Messi Cuccittini,66.415960
259,5,37,Lionel Andrés Messi Cuccittini,Jordi Alba Ramos,31.262278
739,16,18,Manuel Alejandro García Sánchez,Rubén Sobrino Pozuelo,24.957764
1336,30,40,Luis Alberto Suárez Díaz,Ousmane Dembélé,14.909058
1544,35,4,Lionel Andrés Messi Cuccittini,Ivan Rakitić,19.669773
1617,38,26,Lionel Andrés Messi Cuccittini,Ousmane Dembélé,28.246061
1684,40,31,Jordi Alba Ramos,Luis Alberto Suárez Díaz,53.695440
1786,43,30,Jordi Alba Ramos,Ousmane Dembélé,11.005453
1993,47,36,Ousmane Dembélé,Jordi Alba Ramos,11.645600
2392,54,53,Jordi Alba Ramos,Philippe Coutinho Correia,15.316984
2430,55,33,Ousmane Dembélé,Jordi Alba Ramos,6.596969
2501,57,18,Philippe Coutinho Correia,Lionel Andrés Messi Cuccittini,7.940403
2786,65,40,Luis Alberto Suárez Díaz,Lionel Andrés Messi Cuccittini,9.360556
3184,78,15,Ibai Gómez Pérez,Adrián Marín Gómez,41.387558
3340,81,29,Lionel Andrés Messi Cuccittini,Philippe Coutinho Correia,23.212496
3637,89,19,Sergi Roberto Carnicer,Lionel Andrés Messi Cuccittini,9.873196

In [65]:
all_pass_keys = set()

for p in passes["pass"]:
    if isinstance(p, dict):
        all_pass_keys.update(p.keys())

sorted(all_pass_keys)

['aerial_won',
 'angle',
 'assisted_shot_id',
 'body_part',
 'cross',
 'cut_back',
 'deflected',
 'end_location',
 'goal_assist',
 'height',
 'inswinging',
 'length',
 'miscommunication',
 'no_touch',
 'outcome',
 'recipient',
 'shot_assist',
 'straight',
 'switch',
 'technique',
 'through_ball',
 'type']

In [66]:
passes["key_pass"] = passes["pass"].apply(
    lambda x: x.get("shot_assist", False)
    if isinstance(x, dict)
    else False
)

passes["key_pass"].value_counts()

key_pass
False    1147
True       16
Name: count, dtype: int64

In [67]:
passes["assist"] = passes["pass"].apply(
    lambda x: x.get("goal_assist", False)
    if isinstance(x, dict)
    else False
)

assist_stats = (
    passes.groupby("player_name")["assist"]
    .sum()
    .sort_values(ascending=False)
)

assist_stats.head(10)

player_name
Arthur Henrique Ramos de Oliveira Melo    1
Luis Alberto Suárez Díaz                  1
Arturo Erasmo Vidal Pardo                 0
Adrián Marín Gómez                        0
Daniel Alejandro Torres Rojas             0
Fernando Pacheco Flores                   0
Gerard Piqué Bernabéu                     0
Guillermo Alfonso Maripán Loaysa          0
Ibai Gómez Pérez                          0
Ivan Rakitić                              0
Name: assist, dtype: int64

In [68]:
df["through_ball"] = df["pass"].apply(
    lambda x: x.get("through_ball", False)
    if isinstance(x, dict)
    else False
)

In [69]:
df["through_ball"].value_counts()

through_ball
False    3754
True        8
Name: count, dtype: int64

In [70]:
passes["through_ball"] = passes["pass"].apply(
    lambda x: x.get("through_ball", False)
    if isinstance(x, dict)
    else False
)

In [71]:
passes[passes["through_ball"] == True][
    ["minute", "player_name", "recipient", "pass_length"]
]

,minute,player_name,recipient,pass_length
557,11,Lionel Andrés Messi Cuccittini,Luis Alberto Suárez Díaz,41.280140
1617,38,Lionel Andrés Messi Cuccittini,Ousmane Dembélé,28.246061
1684,40,Jordi Alba Ramos,Luis Alberto Suárez Díaz,53.695440
2594,59,Ivan Rakitić,Lionel Andrés Messi Cuccittini,40.459858
3106,74,Sergi Roberto Carnicer,Lionel Andrés Messi Cuccittini,20.865522
3340,81,Lionel Andrés Messi Cuccittini,Philippe Coutinho Correia,23.212496
3419,84,Arthur Henrique Ramos de Oliveira Melo,Luis Alberto Suárez Díaz,16.807735
3655,89,Ivan Rakitić,Lionel Andrés Messi Cuccittini,27.297070

In [72]:
df.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'duration',
 'tactics',
 'related_events',
 'player',
 'position',
 'location',
 'pass',
 'carry',
 'ball_receipt',
 'under_pressure',
 'duel',
 'counterpress',
 'interception',
 'off_camera',
 'ball_recovery',
 'shot',
 'goalkeeper',
 'clearance',
 'block',
 'dribble',
 'foul_committed',
 'foul_won',
 'out',
 'miscontrol',
 'bad_behaviour',
 'substitution',
 'event_type',
 'through_ball']

In [73]:
passes.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'type',
 'possession',
 'possession_team',
 'play_pattern',
 'team',
 'duration',
 'tactics',
 'related_events',
 'player',
 'position',
 'location',
 'pass',
 'carry',
 'ball_receipt',
 'under_pressure',
 'duel',
 'counterpress',
 'interception',
 'off_camera',
 'ball_recovery',
 'shot',
 'goalkeeper',
 'clearance',
 'block',
 'dribble',
 'foul_committed',
 'foul_won',
 'out',
 'miscontrol',
 'bad_behaviour',
 'substitution',
 'event_type',
 'recipient',
 'pass_length',
 'completed',
 'player_name',
 'start_x',
 'end_x',
 'forward_distance',
 'progressive',
 'key_pass',
 'assist',
 'through_ball']

In [74]:
df["related_events"].head()

0                                       NaN
1                                       NaN
2    [757b85ad-ddfe-44d5-b893-c23a9fb709d8]
3    [491e8901-7630-4cc8-b57b-937dddff2eaa]
4    [b56799eb-083a-4e28-bc70-78b77496cdfc]
Name: related_events, dtype: object

In [75]:
df["related_events"].iloc[2]

['757b85ad-ddfe-44d5-b893-c23a9fb709d8']

In [76]:
df["shot"].dropna().iloc[0]

{'statsbomb_xg': 0.07699243,
 'end_location': [120.0, 34.1, 0.9],
 'key_pass_id': '96c89235-1a30-47d0-accd-81309e05f4c3',
 'outcome': {'id': 98, 'name': 'Off T'},
 'first_time': True,
 'technique': {'id': 91, 'name': 'Half Volley'},
 'body_part': {'id': 40, 'name': 'Right Foot'},
 'type': {'id': 87, 'name': 'Open Play'},
 'freeze_frame': [{'location': [91.1, 50.2],
   'player': {'id': 6632, 'name': 'Manuel Alejandro García Sánchez'},
   'position': {'id': 15, 'name': 'Left Center Midfield'},
   'teammate': False},
  {'location': [93.2, 43.7],
   'player': {'id': 6839, 'name': 'Daniel Alejandro Torres Rojas'},
   'position': {'id': 10, 'name': 'Center Defensive Midfield'},
   'teammate': False},
  {'location': [82.9, 59.5],
   'player': {'id': 6581, 'name': 'Jonathan Rodríguez Menéndez'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': False},
  {'location': [103.0, 44.8],
   'player': {'id': 5246, 'name': 'Luis Alberto Suárez Díaz'},
   'position': {'id': 22, 'name': 'Right Center Forward'},
   'teammate': True},
  {'location': [95.4, 53.4],
   'player': {'id': 6379, 'name': 'Sergi Roberto Carnicer'},
   'position': {'id': 12, 'name': 'Right Midfield'},
   'teammate': True},
  {'location': [95.6, 25.4],
   'player': {'id': 5477, 'name': 'Ousmane Dembélé'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': True},
  {'location': [102.1, 29.4],
   'player': {'id': 6618, 'name': 'Martín Aguirregabiria Padilla'},
   'position': {'id': 2, 'name': 'Right Back'},
   'teammate': False},
  {'location': [116.5, 45.6],
   'player': {'id': 6629, 'name': 'Fernando Pacheco Flores'},
   'position': {'id': 1, 'name': 'Goalkeeper'},
   'teammate': False},
  {'location': [107.8, 42.6],
   'player': {'id': 6615, 'name': 'Víctor Laguardia Cisneros'},
   'position': {'id': 3, 'name': 'Right Center Back'},
   'teammate': False},
  {'location': [105.6, 50.0],
   'player': {'id': 6612, 'name': 'Rubén Duarte Sánchez'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': False},
  {'location': [111.3, 51.7],
   'player': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': False}]}

In [77]:
shot_example = df["shot"].dropna().iloc[0]

shot_example.keys()

dict_keys(['statsbomb_xg', 'end_location', 'key_pass_id', 'outcome', 'first_time', 'technique', 'body_part', 'type', 'freeze_frame'])

In [78]:
shot_example["outcome"]

{'id': 98, 'name': 'Off T'}

In [79]:
type(shot_example["outcome"])

dict

In [80]:
shot_example["statsbomb_xg"]

0.07699243

In [81]:

shot_example["statsbomb_xg"] * 100

7.699243

In [82]:
freeze_frame = shot_example["freeze_frame"]

type(freeze_frame)

list

In [83]:
len(freeze_frame)

11

In [84]:
type(shot_example["outcome"])

dict

In [85]:
freeze_frame[0]

{'location': [91.1, 50.2],
 'player': {'id': 6632, 'name': 'Manuel Alejandro García Sánchez'},
 'position': {'id': 15, 'name': 'Left Center Midfield'},
 'teammate': False}

In [86]:
type(freeze_frame[0])

dict

In [87]:
freeze_frame[0]["player"]["name"]

'Manuel Alejandro García Sánchez'

In [88]:
freeze_frame[0]["location"]

[91.1, 50.2]

In [89]:
freeze_frame[0]["teammate"]

False

In [90]:
freeze_frame[0]["teammate"]

False

In [91]:
teammates = [
    player for player in freeze_frame
    if player["teammate"] == True
]

opponents = [
    player for player in freeze_frame
    if player["teammate"] == False
]

In [92]:
len(teammates)

3

In [93]:
len(opponents)

8

In [94]:
import math

actor = next(
    player for player in freeze_frame
    if player.get("actor", False)
)

actor_location = actor["location"]

opponents = [
    player for player in freeze_frame
    if player.get("teammate", False) == False
]

distances = []

for opponent in opponents:
    opponent_location = opponent["location"]

    distance = math.sqrt(
        (opponent_location[0] - actor_location[0]) ** 2 +
        (opponent_location[1] - actor_location[1]) ** 2
    )

    distances.append(distance)

nearest_opponent_distance = min(distances)

print(nearest_opponent_distance)

StopIteration:

In [ ]:
print(freeze_frame)

[{'location': [91.1, 50.2], 'player': {'id': 6632, 'name': 'Manuel Alejandro García Sánchez'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}, {'location': [93.2, 43.7], 'player': {'id': 6839, 'name': 'Daniel Alejandro Torres Rojas'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False}, {'location': [82.9, 59.5], 'player': {'id': 6581, 'name': 'Jonathan Rodríguez Menéndez'}, 'position': {'id': 16, 'name': 'Left Midfield'}, 'teammate': False}, {'location': [103.0, 44.8], 'player': {'id': 5246, 'name': 'Luis Alberto Suárez Díaz'}, 'position': {'id': 22, 'name': 'Right Center Forward'}, 'teammate': True}, {'location': [95.4, 53.4], 'player': {'id': 6379, 'name': 'Sergi Roberto Carnicer'}, 'position': {'id': 12, 'name': 'Right Midfield'}, 'teammate': True}, {'location': [95.6, 25.4], 'player': {'id': 5477, 'name': 'Ousmane Dembélé'}, 'position': {'id': 16, 'name': 'Left Midfield'}, 'teammate': True}, {'location': [102.1, 29.4], 'player': {'id': 6618, 'name': 'Martín Aguirregabiria Padilla'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False}, {'location': [116.5, 45.6], 'player': {'id': 6629, 'name': 'Fernando Pacheco Flores'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}, {'location': [107.8, 42.6], 'player': {'id': 6615, 'name': 'Víctor Laguardia Cisneros'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False}, {'location': [105.6, 50.0], 'player': {'id': 6612, 'name': 'Rubén Duarte Sánchez'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False}, {'location': [111.3, 51.7], 'player': {'id': 6855, 'name': 'Guillermo Alfonso Maripán Loaysa'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False}]

In [ ]:
print("Number of players:", len(freeze_frame))

Number of players: 11

In [ ]:
print("Number of players:", len(freeze_frame))

Number of players: 11

In [ ]:
for i, player in enumerate(freeze_frame):
    print(i, player.keys())

0 dict_keys(['location', 'player', 'position', 'teammate'])
1 dict_keys(['location', 'player', 'position', 'teammate'])
2 dict_keys(['location', 'player', 'position', 'teammate'])
3 dict_keys(['location', 'player', 'position', 'teammate'])
4 dict_keys(['location', 'player', 'position', 'teammate'])
5 dict_keys(['location', 'player', 'position', 'teammate'])
6 dict_keys(['location', 'player', 'position', 'teammate'])
7 dict_keys(['location', 'player', 'position', 'teammate'])
8 dict_keys(['location', 'player', 'position', 'teammate'])
9 dict_keys(['location', 'player', 'position', 'teammate'])
10 dict_keys(['location', 'player', 'position', 'teammate'])

In [ ]:
print(freeze_frame[0])

{'location': [91.1, 50.2], 'player': {'id': 6632, 'name': 'Manuel Alejandro García Sánchez'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False}

In [ ]:
print(df["player"].dropna().iloc[0])

{'id': 6581, 'name': 'Jonathan Rodríguez Menéndez'}

In [ ]:
print(three_sixty[0].keys())

NameError: name 'three_sixty' is not defined

In [ ]:
%whos

Variable            Type             Data/Info
----------------------------------------------
Path                type             <class 'pathlib.Path'>
all_pass_keys       set              {'outcome', 'miscommunica<...>, 'length', 'inswinging'}
assist_stats        Series           Shape: (28,)
data_folder         WindowsPath      open-data-master\data\events
df                  DataFrame        Shape: (3762, 39)
event_files         list             n=4235
events              list             n=3762
file                TextIOWrapper    <_io.TextIOWrapper name='<...>ode='r' encoding='utf-8'>
first_id            str              b56799eb-083a-4e28-bc70-78b77496cdfc
freeze_frame        list             n=11
i                   int              10
json                module           <module 'json' from 'c:\\<...>\Lib\\json\\__init__.py'>
match_file          WindowsPath      open-data-master\data\events\15946.json
math                module           <module 'math' (built-in)>
opponents           list             n=8
os                  module           <module 'os' (frozen)>
p                   dict             n=8
pass_data           dict             n=8
passes              DataFrame        Shape: (1163, 49)
pd                  module           <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
player              dict             n=4
player_stats        DataFrame        Shape: (28, 3)
progressive_stats   Series           Shape: (28,)
shot_example        dict             n=9
teammates           list             n=3

In [ ]:
event_row = df[df["id"] == first_id]

print(event_row["type"])
print(event_row["player"])
print(event_row["location"])

5    {'id': 42, 'name': 'Ball Receipt*'}
Name: type, dtype: object
5    {'id': 6855, 'name': 'Guillermo Alfonso Maripá...
Name: player, dtype: object
5    [33.8, 28.0]
Name: location, dtype: object

In [ ]:
print(shot_example.keys())

dict_keys(['statsbomb_xg', 'end_location', 'key_pass_id', 'outcome', 'first_time', 'technique', 'body_part', 'type', 'freeze_frame'])

In [ ]:
for event in events:
    if event.get("shot") == shot_example:
        shot_event = event
        break

print("Player:", shot_event["player"])
print("Location:", shot_event["location"])
print("Event type:", shot_event["type"])

Player: {'id': 5503, 'name': 'Lionel Andrés Messi Cuccittini'}
Location: [111.5, 52.9]
Event type: {'id': 16, 'name': 'Shot'}

In [ ]:
print(df.columns.tolist())

['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics', 'related_events', 'player', 'position', 'location', 'pass', 'carry', 'ball_receipt', 'under_pressure', 'duel', 'counterpress', 'interception', 'off_camera', 'ball_recovery', 'shot', 'goalkeeper', 'clearance', 'block', 'dribble', 'foul_committed', 'foul_won', 'out', 'miscontrol', 'bad_behaviour', 'substitution', 'event_type', 'through_ball']

In [ ]:
columns_table = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Column Name": df.columns
})

columns_table

    Column Number      Column Name
0               1               id
1               2            index
2               3           period
3               4        timestamp
4               5           minute
5               6           second
6               7             type
7               8       possession
8               9  possession_team
9              10     play_pattern
10             11             team
11             12         duration
12             13          tactics
13             14   related_events
14             15           player
15             16         position
16             17         location
17             18             pass
18             19            carry
19             20     ball_receipt
20             21   under_pressure
21             22             duel
22             23     counterpress
23             24     interception
24             25       off_camera
25             26    ball_recovery
26             27             shot
27             28       goalkeeper
28             29        clearance
29             30            block
30             31          dribble
31             32   foul_committed
32             33         foul_won
33             34              out
34             35       miscontrol
35             36    bad_behaviour
36             37     substitution
37             38       event_type
38             39     through_ball

In [ ]:
print(passes.iloc[0])

id                               549567bd-36de-4ac8-b8dc-6b5d3f1e4be8
index                                                               5
period                                                              1
timestamp                                                00:00:00.575
minute                                                              0
second                                                              0
type                                       {'id': 30, 'name': 'Pass'}
possession                                                          2
possession_team               {'id': 206, 'name': 'Deportivo Alavés'}
play_pattern                       {'id': 9, 'name': 'From Kick Off'}
team                          {'id': 206, 'name': 'Deportivo Alavés'}
duration                                                     2.015669
tactics                                                           NaN
related_events                 [b56799eb-083a-4e28-bc70-78b77496cdfc]
player              {'id': 6581, 'name': 'Jonathan Rodríguez Menén...
position                          {'id': 16, 'name': 'Left Midfield'}
location                                                 [61.0, 40.1]
pass                {'recipient': {'id': 6855, 'name': 'Guillermo ...
carry                                                             NaN
ball_receipt                                                      NaN
under_pressure                                                    NaN
duel                                                              NaN
counterpress                                                      NaN
interception                                                      NaN
off_camera                                                        NaN
ball_recovery                                                     NaN
shot                                                              NaN
goalkeeper                                                        NaN
clearance                                                         NaN
block                                                             NaN
dribble                                                           NaN
foul_committed                                                    NaN
foul_won                                                          NaN
out                                                               NaN
miscontrol                                                        NaN
bad_behaviour                                                     NaN
substitution                                                      NaN
event_type                                                       Pass
recipient                            Guillermo Alfonso Maripán Loaysa
pass_length                                                  29.76995
completed                                                         Yes
player_name                               Jonathan Rodríguez Menéndez
start_x                                                          61.0
end_x                                                            33.8
forward_distance                                                -27.2
progressive                                                     False
key_pass                                                        False
assist                                                          False
through_ball                                                    False
Name: 4, dtype: object

In [ ]:
import math

actor_location = shot_event["location"]

opponents = [
    player for player in freeze_frame
    if player["teammate"] == False
]

distances = []

for opponent in opponents:
    opponent_location = opponent["location"]

    distance = math.sqrt(
        (opponent_location[0] - actor_location[0]) ** 2 +
        (opponent_location[1] - actor_location[1]) ** 2
    )

    distances.append(distance)

nearest_opponent_distance = min(distances)

print("Distances:", distances)
print("Nearest opponent distance:", nearest_opponent_distance)

Distances: [20.577900767571027, 20.482431496284804, 29.35166094107793, 25.31027459353217, 8.848163651289456, 10.94440496326776, 6.574191965557445, 1.2165525060596403]
Nearest opponent distance: 1.2165525060596403

In [ ]:
nearest_index = distances.index(min(distances))

nearest_opponent = opponents[nearest_index]

print("Nearest opponent:", nearest_opponent["player"]["name"])
print("Opponent location:", nearest_opponent["location"])
print("Distance:", distances[nearest_index])

Nearest opponent: Guillermo Alfonso Maripán Loaysa
Opponent location: [111.3, 51.7]
Distance: 1.2165525060596403

In [ ]:
nearby_opponents = 0

for distance in distances:
    if distance <= 5:
        nearby_opponents += 1

print("Opponents within 5 units:", nearby_opponents)

Opponents within 5 units: 1

In [ ]:
nearby_players = []

for opponent, distance in zip(opponents, distances):
    if distance <= 5:
        nearby_players.append({
            "name": opponent["player"]["name"],
            "distance": distance,
            "location": opponent["location"]
        })

print(nearby_players)

[{'name': 'Guillermo Alfonso Maripán Loaysa', 'distance': 1.2165525060596403, 'location': [111.3, 51.7]}]

In [95]:
import math

def get_nearest_opponent(freeze_frame):
    
    if not isinstance(freeze_frame, list):
        return None, None

    actor = next(
        (
            player for player in freeze_frame
            if player.get("actor") == True
        ),
        None
    )

    if actor is None:
        return None, None

    actor_location = actor.get("location")

    if actor_location is None:
        return None, None

    opponents = [
        player for player in freeze_frame
        if player.get("teammate") == False
        and player.get("location") is not None
    ]

    if len(opponents) == 0:
        return None, None

    distances = []

    for opponent in opponents:
        
        opponent_location = opponent["location"]

        distance = math.sqrt(
            (opponent_location[0] - actor_location[0]) ** 2 +
            (opponent_location[1] - actor_location[1]) ** 2
        )

        distances.append(distance)

    nearest_index = distances.index(min(distances))

    nearest_opponent = opponents[nearest_index]

    nearest_name = nearest_opponent["player"]["name"]

    nearest_distance = distances[nearest_index]

    return nearest_name, nearest_distance

In [97]:
print(df.columns.tolist())

['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics', 'related_events', 'player', 'position', 'location', 'pass', 'carry', 'ball_receipt', 'under_pressure', 'duel', 'counterpress', 'interception', 'off_camera', 'ball_recovery', 'shot', 'goalkeeper', 'clearance', 'block', 'dribble', 'foul_committed', 'foul_won', 'out', 'miscontrol', 'bad_behaviour', 'substitution', 'event_type', 'through_ball']

In [99]:
%whos

Variable               Type             Data/Info
-------------------------------------------------
Path                   type             <class 'pathlib.Path'>
all_pass_keys          set              {'height', 'recipient', '<...>straight', 'shot_assist'}
assist_stats           Series           Shape: (28,)
data_folder            WindowsPath      open-data-master\data\events
df                     DataFrame        Shape: (3762, 39)
event_files            list             n=4235
events                 list             n=3762
file                   TextIOWrapper    <_io.TextIOWrapper name='<...>ode='r' encoding='utf-8'>
first_id               str              b56799eb-083a-4e28-bc70-78b77496cdfc
freeze_frame           list             n=11
get_nearest_opponent   function         <function get_nearest_opp<...>nt at 0x0000017EE7816770>
json                   module           <module 'json' from 'c:\\<...>\Lib\\json\\__init__.py'>
match_file             WindowsPath      open-data-master\data\events\15946.json
math                   module           <module 'math' (built-in)>
opponents              list             n=8
os                     module           <module 'os' (frozen)>
p                      dict             n=8
pass_data              dict             n=8
passes                 DataFrame        Shape: (1163, 49)
pd                     module           <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
player_stats           DataFrame        Shape: (28, 3)
progressive_stats      Series           Shape: (28,)
shot_example           dict             n=9
teammates              list             n=3

In [101]:
from pathlib import Path

base = Path("open-data-master")

for folder in base.rglob("*"):
    if folder.is_dir() and "360" in folder.name.lower():
        print(folder)

In [102]:
matches = list(base.rglob("15946.json"))

for match in matches:
    print(match)

open-data-master\data\events\15946.json
open-data-master\data\lineups\15946.json

In [103]:
matches = list(base.rglob("15946.json"))

for match in matches:
    print(match)

open-data-master\data\events\15946.json
open-data-master\data\lineups\15946.json

In [104]:
base = Path("open-data-master")

for folder in base.rglob("*"):
    if folder.is_dir() and "three" in folder.name.lower():
        print(folder)

open-data-master\data\three-sixty

In [105]:
three_sixty_folder = Path("open-data-master/data/three-sixty")

three_sixty_files = list(three_sixty_folder.glob("*.json"))

print("Number of 360 files:", len(three_sixty_files))

for file in three_sixty_files[:20]:
    print(file.name)

Number of 360 files: 426
3764440.json
3764661.json
3773369.json
3773372.json
3773377.json
3773386.json
3773387.json
3773403.json
3773415.json
3773428.json
3773457.json
3773466.json
3773474.json
3773477.json
3773497.json
3773523.json
3773526.json
3773547.json
3773552.json
3773565.json

In [107]:
match_id = "3764440"

events_file = Path(f"open-data-master/data/events/{match_id}.json")
three_sixty_file = Path(f"open-data-master/data/three-sixty/{match_id}.json")

with open(events_file, "r", encoding="utf-8") as file:
    events_360_match = json.load(file)

with open(three_sixty_file, "r", encoding="utf-8") as file:
    data_360 = json.load(file)

df_match = pd.DataFrame(events_360_match)
df_360 = pd.DataFrame(data_360)

In [108]:
print("Events shape:", df_match.shape)
print("360 shape:", df_360.shape)

print("\nEvents columns:")
print(df_match.columns.tolist())

print("\n360 columns:")
print(df_360.columns.tolist())

Events shape: (4160, 36)
360 shape: (3914, 3)

Events columns:
['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics', 'related_events', 'player', 'position', 'location', 'pass', 'carry', 'under_pressure', 'dribble', 'shot', 'goalkeeper', 'out', 'ball_recovery', 'duel', 'ball_receipt', 'clearance', 'off_camera', 'counterpress', 'interception', 'foul_won', 'foul_committed', 'substitution', '50_50', 'injury_stoppage']

360 columns:
['event_uuid', 'visible_area', 'freeze_frame']

In [109]:
df_match = df_match.merge(
    df_360[["event_uuid", "freeze_frame"]],
    left_on="id",
    right_on="event_uuid",
    how="left"
)

In [110]:
print(df_match.shape)
print("freeze_frame" in df_match.columns)

(4160, 38)
True

In [111]:
print(df_match["freeze_frame"].notna().sum())

3914

In [114]:
df_match[
    [
        "player",
        "type",
        "nearest_opponent",
        "nearest_opponent_distance"
    ]
].head(10)

KeyError: "['nearest_opponent', 'nearest_opponent_distance'] not in index"

In [116]:
import math

def get_nearest_opponent(freeze_frame):

    if not isinstance(freeze_frame, list):
        return None, None

    actor = next(
        (
            player for player in freeze_frame
            if player.get("actor") == True
        ),
        None
    )

    if actor is None:
        return None, None

    actor_location = actor.get("location")

    if actor_location is None:
        return None, None

    opponents = [
        player for player in freeze_frame
        if player.get("teammate") == False
        and player.get("location") is not None
    ]

    if len(opponents) == 0:
        return None, None

    distances = []

    for opponent in opponents:

        opponent_location = opponent["location"]

        distance = math.sqrt(
            (opponent_location[0] - actor_location[0]) ** 2 +
            (opponent_location[1] - actor_location[1]) ** 2
        )

        distances.append(distance)

    nearest_index = distances.index(min(distances))

    nearest_opponent = opponents[nearest_index]

    nearest_location = nearest_opponent["location"]
    nearest_distance = distances[nearest_index]

    return nearest_location, nearest_distance

In [117]:
df_match[
    ["nearest_opponent_location", "nearest_opponent_distance"]
] = (
    df_match["freeze_frame"]
    .apply(get_nearest_opponent)
    .apply(pd.Series)
)

In [118]:
df_match[
    [
        "player",
        "type",
        "nearest_opponent_location",
        "nearest_opponent_distance"
    ]
].dropna().head(10)

,player,type,nearest_opponent_location,nearest_opponent_distance
4,"{'id': 12072, 'name': 'Pere Milla Peña'}","{'id': 30, 'name': 'Pass'}","[52.273950315181956, 38.42847753920154]",8.884702
5,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 42, 'name': 'Ball Receipt*'}","[58.525749040615366, 55.616830930614796]",10.734909
6,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 43, 'name': 'Carry'}","[58.525749040615366, 55.616830930614796]",10.734909
7,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 30, 'name': 'Pass'}","[58.99838057189282, 51.40565894914739]",8.898384
8,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 42, 'name': 'Ball Receipt*'}","[55.378889386232515, 48.42932763485586]",22.101975
9,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 43, 'name': 'Carry'}","[55.378889386232515, 48.42932763485586]",22.101975
10,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 30, 'name': 'Pass'}","[55.09060399419812, 49.287765588342715]",21.169590
11,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 42, 'name': 'Ball Receipt*'}","[47.39650916051406, 28.33798319316506]",15.873415
12,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 43, 'name': 'Carry'}","[47.39650916051406, 28.33798319316506]",15.873415
13,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 30, 'name': 'Pass'}","[42.95139938794394, 27.757633866350695]",9.798178

In [119]:
test_frame = df_match["freeze_frame"].dropna().iloc[0]

result = get_nearest_opponent(test_frame)

print(result)

([52.273950315181956, 38.42847753920154], 8.88470175851657)

In [120]:
nearest_results = df_match["freeze_frame"].apply(get_nearest_opponent)

In [121]:
df_match[
    ["nearest_opponent_location", "nearest_opponent_distance"]
] = pd.DataFrame(
    nearest_results.tolist(),
    index=df_match.index
)

In [122]:
df_match[
    [
        "player",
        "type",
        "nearest_opponent_location",
        "nearest_opponent_distance"
    ]
].dropna().head(10)

,player,type,nearest_opponent_location,nearest_opponent_distance
4,"{'id': 12072, 'name': 'Pere Milla Peña'}","{'id': 30, 'name': 'Pass'}","[52.273950315181956, 38.42847753920154]",8.884702
5,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 42, 'name': 'Ball Receipt*'}","[58.525749040615366, 55.616830930614796]",10.734909
6,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 43, 'name': 'Carry'}","[58.525749040615366, 55.616830930614796]",10.734909
7,"{'id': 24517, 'name': 'José Raúl Gutiérrez Par...","{'id': 30, 'name': 'Pass'}","[58.99838057189282, 51.40565894914739]",8.898384
8,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 42, 'name': 'Ball Receipt*'}","[55.378889386232515, 48.42932763485586]",22.101975
9,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 43, 'name': 'Carry'}","[55.378889386232515, 48.42932763485586]",22.101975
10,"{'id': 24169, 'name': 'Gonzalo Cacicedo Verdú'}","{'id': 30, 'name': 'Pass'}","[55.09060399419812, 49.287765588342715]",21.169590
11,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 42, 'name': 'Ball Receipt*'}","[47.39650916051406, 28.33798319316506]",15.873415
12,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 43, 'name': 'Carry'}","[47.39650916051406, 28.33798319316506]",15.873415
13,"{'id': 9857, 'name': 'José Manuel Sánchez Guil...","{'id': 30, 'name': 'Pass'}","[42.95139938794394, 27.757633866350695]",9.798178

In [123]:
df_match["event_type"] = df_match["type"].apply(
    lambda x: x.get("name") if isinstance(x, dict) else x
)

In [124]:
pass_shot_360 = df_match[
    df_match["event_type"].isin(["Pass", "Shot"])
].copy()

In [125]:
print("Total Pass + Shot events:")
print(len(pass_shot_360))

print("\nBreakdown:")
print(pass_shot_360["event_type"].value_counts())

print("\nEvents with nearest-opponent distance:")
print(pass_shot_360["nearest_opponent_distance"].notna().sum())

print("\nEvents without nearest-opponent distance:")
print(pass_shot_360["nearest_opponent_distance"].isna().sum())

Total Pass + Shot events:
1230

Breakdown:
event_type
Pass    1215
Shot      15
Name: count, dtype: int64

Events with nearest-opponent distance:
1165

Events without nearest-opponent distance:
65